import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SolanaProviders } from "./providers/solana-wallet";
import { ChakraProviders } from "./providers/chakra";
import { Toaster } from "@/components/ui/sonner";
import { EventNotifications } from "@/components/EventNotifications";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="ru">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ChakraProviders>
          <SolanaProviders>
            {children}
            <EventNotifications />
            <Toaster />
          </SolanaProviders>
        </ChakraProviders>
      </body>
    </html>
  );
}

 
